name: Deference Design
favicon: null
layout_spectrum: 0
typography_spectrum: 0.54285
title: DEFERENCE DESIGN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#FBA575'
    - '#C74A6D'
    - '#41151F'
    - '#914C41'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
